CREATE DATABASE jchat;

CREATE TABLE IF NOT EXISTS users (
  index SERIAL PRIMARY KEY UNIQUE NOT NULL,
  email TEXT UNIQUE NOT NULL,
  username TEXT NOT NULL,
  hash TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS channels (
  index SERIAL PRIMARY KEY UNIQUE NOT NULL,
  cid INTEGER NOT NULL,
  user_id INTEGER,
  owner_id INTEGER
);

CREATE TABLE IF NOT EXISTS messages(
  index SERIAL PRIMARY KEY UNIQUE NOT NULL,
  date TIMESTAMP NOT NULL,
  content TEXT NOT NULL,
  source_id INTEGER NOT NULL,
  channel_id INTEGER NOT NULL,
  CONSTRAINT source_id_fk FOREIGN KEY (source_id) REFERENCES users(index)
);